### PR TITLE
Remove some potential retain cycles.

### PR DESCRIPTION
**Pull request by jeff-h**
This PR removes a few potential retain cycle culprits. Unfortunately there are still several leaks but tracking them can be quite time consuming.

### CODE REVIEW

**Comment by glushchenko** [comment]
@jeff-h seems like tests failed

**Comment by jeff-h** [comment]
@glushchenko yeah, i noticed that. Is there any feedback from Travis as to why it failed? I poked around and hardly found anything useful :(

**Comment by glushchenko** [comment]
https://travis-ci.com/glushchenko/fsnotes/jobs/234304103

> /Users/travis/build/glushchenko/fsnotes/FSNotes iOS/CloudDriveManager.swift:15:22: error: 'weak' variable should have optional type 'ViewController?'
1156    private weak var delegate: ViewController

**Comment by glushchenko** [comment]
@jeff-h seems like `FSNotes iOS/CloudDriveManager.swift` doing nothing, ViewController and CloudDriveManager should persist in all app running cycle. Nothing GC here.

```swift
private weak var delegate: ViewController
```

**Comment by jeff-h** [comment]
@glushchenko sorry I procrastinated — thanks for sorting all that out!

**Pull request merged**
