### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by Pusnow**
Add Korean translation for

- FSNotes
- FSNotes iOS
- FSNotes iOS Share

### CODE REVIEW

**Comment by glushchenko** [comment]
Awesome! I will try later

**Comment by glushchenko** [comment]
@Pusnow here only small part of translation.

Please download XLIFF tool and open this file. 

[ko.xliff.zip](https://github.com/glushchenko/fsnotes/files/3692413/ko.xliff.zip)

All strings should be translated.

**Comment by Pusnow** [comment]
Done!

[ko.zip](https://github.com/glushchenko/fsnotes/files/3692812/ko.zip)

**Comment by glushchenko** [comment]
Merged in dev branch, seems like all OK. Thanks @Pusnow 

Translation will be available in next release:

image

**Comment by Pusnow** [comment]
Great!

**Pull request closed without merging**
