### PR TITLE
Add preference setting for cell spacing

### PR DESCRIPTION
**Pull request by jeff-h**
I like a bit of whitespace in my notes listing, but I can imagine others may not. I've added this as a user preference.

### CODE REVIEW

**Comment by jeff-h** [comment]
Ideally I think the cell contents (note title, date and preview) should be centred vertically in its cell but I wasn't sure how to achieve this — I usually use IB autolayout for that sort of thing. Do you have any thoughts on how to implement this?

**Comment by glushchenko** [comment]
> Ideally I think the cell contents (note title, date and preview) should be centred vertically in its cell but I wasn't sure how to achieve this — I usually use IB autolayout for that sort of thing. Do you have any thoughts on how to implement this?

I'll try fix in next release 🍻

**Comment by glushchenko** [comment]
Fixed some troubles with pin, horizontal view and maximum lines number

**Comment by jeff-h** [comment]
Oh dear — sorry about all those edge cases!

**Pull request merged**
