### PR TITLE
Update FSNotes/zh-Hans.lproj/Localizable.strings

### PR DESCRIPTION
**Pull request by holton-jiang**
Improved translations for some Chinese Simplified.

### CODE REVIEW

**Comment by glushchenko** [comment]
OMG, what going on? Why so many requests?

**Comment by holton-jiang** [comment]
> OMG, what going on? Why so many requests?

I'm sorry, I don't know how to use GitHub.

**Comment by glushchenko** [comment]
No problem, you can just mail translation files. I am appreciate your work.

**Comment by holton-jiang** [comment]
> 没问题，你可以邮寄翻译文件。我很感激你的工作。

Basically all Chinese Simplified translations have been improved.

**Pull request merged**
