### PR TITLE
Fix #710: Git crash

### LINKED ISSUE #710: Crash when right clicking note preview
**Describe the bug**
Crash when right clicking note preview after search results

**To Reproduce**
1. Right click list item preview
2. Crash

**Expected behavior**
Context menu should be shown

**Actual behavior**
Crash

**Workaround**
Use 3.8.2

**Supporting Files**
[FSNotes_2019-10-10-164956_matt.crash.zip](https://github.com/glushchenko/fsnotes/files/3713457/FSNotes_2019-10-10-164956_matt.crash.zip)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 3.9.1 & 3.9.0

### PR DESCRIPTION
**Pull request by buddax2**
This fixes the crash described in #710

There was a crash in case if you right-click on a note in the note list. It was because the git binary is placed in `FSNotes.app/Contents/Resources/git` but not in `FSNotes.app/Contents/MacOS/git`.

Also replaced deprecated `process.launch()` with the new `process.run()` method

### CODE REVIEW

**Comment by gingerbeardman** [comment]
Super! 

Fixes my longstanding #710

**Comment by glushchenko** [comment]
Really fixed? Git history not working for me completely ...

**Comment by buddax2** [comment]
@glushchenko I just verified on the latest build from master and it does work for me. Is there a crash or any errors in the debug output?

**Comment by glushchenko** [comment]
Bundle.main.path(forResource: "git", ofType: "") always return null. Tryed on macOS 10.14 and macOS 10.15

**Comment by buddax2** [comment]
For some reason when I build and run the app git is placed inside the `FSNotes.app/Contents/Resources` folder. But I just downloaded this build https://github.com/glushchenko/fsnotes/releases/download/4.0.19/FSNotes_4.0.19.zip and git is placed in `FSNotes.app/Contents/MacOS/`.

I assume you build with some scripts or continuous delivery system which puts git into `FSNotes.app/Contents/MacOS/`. Should I change it back?

**Comment by john-griffin** [comment]
Git integration is completely broken for me in 4.0.19

**Comment by buddax2** [comment]
@glushchenko I made a fix for this but for some reason it has conflicts (PR compares with an old version of the Git.swift file)

**Pull request merged**
