### PR TITLE
Added title fuzzy search for wikilink insertion.

### PR DESCRIPTION
**Pull request by guoc**

### CODE REVIEW

**Comment by gingerbeardman** [comment]
Looks good to me. @glushchenko ?

**Comment by glushchenko** [comment]
@gingerbeardman wil be tested ASAP, thanks.

**Comment by glushchenko** [comment]
Auto-completion is very slow for me.

**Comment by guoc** [comment]
> Auto-completion is very slow for me.

How many notes do you have? I guess it's probably caused by slow file I/O.

**Comment by guoc** [comment]
@glushchenko @gingerbeardman I've test the issue with 10,000 notes generated by the following code (titled by UUID),

```swift
for _ in 1...10_000 {
    vc.createNote(content: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.")
}
```

When debugging, the fuzzy search is indeed slow. When profiling using Xcode Instruments, it's still a little slow, but looks ok for me. The screenshot below is recorded while profiling.

fsnotes-fuzzy-search

In the recent commit, I also updated the search to case insensitive. (It's not supposed to affect the profiling above a lot.)

**Comment by gingerbeardman** [comment]
Maybe it can be an option? And we can gauge response in a beta?

**Comment by glushchenko** [comment]
I'll try today thanks

**Comment by glushchenko** [comment]
I have 1442 notes, and it slows down a lot. In my database Titles multiple words in titles, not one like in sampel above. May be problem in this.

**Comment by glushchenko** [comment]
Please enable in preferences one option - "First line as title" and try it.

**Comment by guoc** [comment]
@glushchenko I tested with the notes data from https://github.com/Zettelkasten-Method/10000-markdown-files, and also enabled "First line as title" option, it works well just like the previous screenshot. Did you test with Xcode menu Product -> Archive result app or just in debug mode? The auto completion in debug is much slower.

**Comment by glushchenko** [comment]
I will try this dataset tomorrow, thanks.

**Comment by glushchenko** [comment]
I can confirm, this not slow down search. But why exact results has score lower than not found? I have title "phpunit" and this lower than "php, bla, bla, bla".

**Pull request closed without merging**
