### PR TITLE
Change sidebar background to system constant

### PR DESCRIPTION
**Pull request by nth-chile**
Change sidebar background from custom color to .windowBackgroundColor

https://developer.apple.com/documentation/appkit/nscolor/1528630-windowbackgroundcolor

### CODE REVIEW

**Comment by glushchenko** [comment]
What is it?

image

**Comment by nth-chile** [comment]
Hey @glushchenko, what do you mean?

**Comment by nth-chile** [comment]
I think because there is another component there. Mine is like that on version 6.8.0. It's always been like that for me

Screenshot 2024-07-12 at 9 00 42 AM

**Comment by glushchenko** [comment]
Don't worry, seems i know how to fix it.

https://github.com/glushchenko/fsnotes/commit/e6b0dde9d33ec33d7dc6689162f84fa1448f7ddc

It happens in light theme only.

**Comment by glushchenko** [comment]
Looks good now. Thank you for PR

**Pull request merged**
