### PR TITLE
Update Localizable format

### PR DESCRIPTION
**Pull request by VChristinne**
Hey, I noticed that you were using the old format of Localizable, so I updated it to the new format (String Catalog) and added the pt-BR language. But I couldn't test it.

### CODE REVIEW

**Comment by glushchenko** [comment]
Hello, @VChristinne 

Where is the translation for storyboard?

image

**Comment by VChristinne** [comment]
@glushchenko it's here for me
Screenshot 2023-10-15 at 9 58 04 PM

**Comment by VChristinne** [comment]
Oh ok, I got it now, I was talk about to String Catalog not the Storyboard. My bad.

**Comment by glushchenko** [comment]
I cannot accept this without 100% translation.

**Comment by VChristinne** [comment]
I updated now.

**Comment by glushchenko** [comment]
Thank you. I will try to check it ASAP

**Comment by glushchenko** [comment]
@VChristinne Please check this pre release build, some changes may be needed: 

[FSNotes.zip](https://github.com/glushchenko/fsnotes/files/12968272/FSNotes.zip)

**Comment by VChristinne** [comment]
@glushchenko LGTM, do you want to change anything in the translation?

**Pull request closed without merging**
