### PR TITLE
WIP: Extract core code into framework

### PR DESCRIPTION
**Pull request by clayreimann**
There appears to be a lot of code that is shared between the Mac and iOS apps, however it is littered with conditional compilation and appears to be prone to leaky abstractions. This is my stab at moving shared code out into frameworks that are embedded into their respective applications.

During this process I'm adding as many tests unit tests as I can because I see there aren't any tests in this project yet.

### CODE REVIEW

**Comment by gingerbeardman** [comment]
Loving your work!

**Comment by clayreimann** [comment]
I’ll declare victory on this when I have extracted the user settings management. At that point you can let me know if you like the direction this PR takes the project and, if so, I’ll continue in subsequent PRs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glushchenko** [comment]
Good job! But i have some troubles with merge 🙂

**Comment by glushchenko** [comment]
Of course we are need in contributors. Refactoring is good thing.

**Comment by gingerbeardman** [comment]
I think a merge this "big" could take some time. What are the problems?

Maybe it's easier to give clay permission to do it?

**Comment by clayreimann** [comment]
I rebased on master this morning, and I’m happy to rebase on master periodically as I go. Will that be fine, or do you have another branch I should develop from?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
